export const SERVER_TO_CLIENT = 'SERVER_TO_CLIENT';
export const CLIENT_TO_SERVER = 'CLIENT_TO_SERVER';

// CONSTANTS SHARED WITH THE CLIENT - how, we will figure out later
export const NOTIFICATION_SET = 'NOTIFICATION_SET';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const PROMPT_CREATE_CHARACTER = 'PROMPT_CREATE_CHARACTER';