// CHARACTER
export const CHARACTER_ONLINE_ADD = 'CHARACTER_ONLINE_ADD'; //ADD_ONLINE_PLAYER
export const CHARACTER_ONLINE_REMOVE = 'CHARACTER_ONLINE_REMOVE'; //REMOVE_ONLINE_PLAYER
export const CHARACTER_UPDATE = 'CHARACTER_UPDATE'; // UPDATE_CHARACTER
export const CHARACTER_EQUIP_ITEM = 'CHARACTER_EQUIP_ITEM'; // EQUIP_ITEM
export const CHARACTER_UNEQUIP_ITEM = 'CHARACTER_UNEQUIP_ITEM'; // UNEQUIP_ITEM
export const CHARACTER_MOVE_ITEM = 'CHARACTER_MOVE_ITEM';
export const CHARACTER_LEFT_GRID = 'CHARACTER_LEFT_GRID'; // LEFT_GRID
export const CHARACTER_JOINED_GRID = 'CHARACTER_JOINED_GRID'; // JOINED_GRID
export const CHARACTER_MOVE = 'CHARACTER_MOVE'; // MOVE_CHARACTER
export const CHARACTERS_GET_LIST = 'CHARACTERS_GET_LIST';
export const CHARACTERS_LIST = 'CHARACTERS_LIST';
export const CHARACTER_LOGIN = 'CHARACTER_LOGIN';
export const CHARACTER_CREATE_ERROR = 'CHARACTER_CREATE_ERROR';
export const CHARACTER_CREATE_SUCCESS = 'CHARACTER_CREATE_SUCCESS';
export const CHARACTER_LOGOUT = 'CHARACTER_LOGOUT'; // GAME_LOGOUT
export const CHARACTER_REMOTE_LOGOUT = 'CHARACTER_REMOTE_LOGOUT'; // REMOTE_LOGOUT

// COMMAND
export const COMMAND_CHAT_COMMAND = 'COMMAND_CHAT_COMMAND'; // GAME_COMMAND
export const COMMAND_CHAT_MESSAGE = 'COMMAND_CHAT_MESSAGE'; // CHAT_MESSAGE

// ITEM
export const ITEM_GROUND_ITEMS = 'ITEM_GROUND_ITEMS'; // UPDATE_GROUND_ITEMS

// MAP
export const MAP_GRID_DETAILS = 'MAP_GRID_DETAILS'; // JOIN_GRID
export const MAP_GET_LIST = 'MAP_GET_LIST'; // MAPS_GET_LIST
export const MAP_LIST = 'MAP_LIST'; // MAPS_LIST

// NPC
export const NPC_JOINED_GRID = 'NPC_JOINED_GRID';
export const NPC_LEFT_GRID = 'NPC_LEFT_GRID';
export const NPC_GRID_DETAILS = 'NPC_GRID_DETAILS'; // UPDATE_GRID_NPCS

// SHOP
export const SHOP_ITEM_PRICE = 'SHOP_ITEM_PRICE';
export const SHOP_GET_PRICE = 'SHOP_GET_PRICE';
export const SHOP_SELL = 'SHOP_SELL';
export const SHOP_BUY = 'SHOP_BUY';
export const SHOP_LOAD = 'SHOP_LOAD';
export const SHOP_UPDATE = 'SHOP_UPDATE';
export const SHOP_EVENT = 'SHOP_EVENT';

// USER
export const USER_AUTHENTICATE = 'USER_AUTHENTICATE'; // ACCOUNT_AUTHENTICATE
export const USER_AUTHENTICATE_ERROR = 'USER_AUTHENTICATE_ERROR'; // ACCOUNT_AUTHENTICATE_ERROR
export const USER_AUTHENTICATE_SUCCESS = 'USER_AUTHENTICATE_SUCCESS'; // ACCOUNT_AUTHENTICATE_SUCCESS
export const USER_LOGOUT = 'USER_LOGOUT'; // ACCOUNT_LOGOUT

// GAME
export const GAME_EVENT = 'GAME_EVENT'; // NEW_EVENT
export const GAME_NEWS = 'GAME_NEWS'; // NEWS_UPDATE
export const NOTIFICATION_SET = 'NOTIFICATION_SET';
