export const ADD_ONLINE_PLAYER = 'ADD_ONLINE_PLAYER';
export const REMOVE_ONLINE_PLAYER = 'REMOVE_ONLINE_PLAYER';
export const UPDATE_CHARACTER = 'UPDATE_CHARACTER';
export const EQUIP_ITEM = 'EQUIP_ITEM';
export const UNEQUIP_ITEM = 'UNEQUIP_ITEM';
export const JOIN_GRID = 'JOIN_GRID';
export const MOVE_CHARACTER = 'MOVE_CHARACTER';