export const SERVER_LOAD_ITEM = 'SERVER_LOAD_ITEM';
export const SERVER_DROP_ITEM = 'SERVER_DROP_ITEM';
export const SERVER_PICKUP_ITEM = 'SERVER_PICKUP_ITEM';
export const CLIENT_DROP_ITEM = 'CLIENT_DROP_ITEM';