export const AUTH_STRATEGIES_SAVE = 'AUTH_STRATEGIES_SAVE';
export const AUTH_STRATEGIES_GET = 'AUTH_STRATEGIES_GET';
export const AUTH_PASSWORD_RESET = 'AUTH_PASSWORD_RESET';
export const AUTH_LINK = 'AUTH_LINK';
export const AUTH_UNLINK = 'AUTH_UNLINK';
export const AUTH_SIGNUP = 'AUTH_SIGNUP';
export const AUTH_PROVIDER = 'AUTH_PROVIDER';
export const AUTH_SAVE = 'AUTH_SAVE';
