export const LEAVE_GRID = 'LEAVE_GRID';
export const JOIN_GRID = 'JOIN_GRID';
export const JOINED_GRID = 'JOINED_GRID';
export const LEFT_GRID = 'LEFT_GRID';
export const UPDATE_GROUND_ITEMS = 'UPDATE_GROUND_ITEMS';

export const CLIENT_LOAD_PLAYER_MAP = 'CLIENT_LOAD_PLAYER_MAP';
export const CLIENT_LOAD_GRID = 'CLIENT_LOAD_GRID';
export const CLIENT_PICKUP_ITEM = 'CLIENT_PICKUP_ITEM';
export const CLIENT_DROP_MULTIPLE_ITEMS = 'CLIENT_DROP_MULTIPLE_ITEMS';

export const NPC_JOINED_GRID = 'NPC_JOINED_GRID';
export const NPC_LEFT_GRID = 'NPC_LEFT_GRID';
