export const CHARACTERS_LIST = 'CHARACTERS_LIST';
export const CHARACTERS_GET_LIST = 'CHARACTERS_GET_LIST';
export const CHARACTER_LOGIN = 'CHARACTER_LOGIN';
export const CHARACTER_CREATE = 'CHARACTER_CREATE';
export const CHARACTER_CREATE_SUCCESS = 'CHARACTER_CREATE_SUCCESS';
export const UPDATE_CHARACTER = 'UPDATE_CHARACTER';
export const MOVE_CHARACTER = 'MOVE_CHARACTER';