export const ACCOUNT_AUTHENTICATE_SAVE = 'ACCOUNT_AUTHENTICATE_SAVE';
export const USER_SIGNUP = 'USER_SIGNUP';
export const USER_DETAILS_GET = 'USER_DETAILS_GET';
export const USER_DETAILS = 'USER_DETAILS';
export const USER_DETAILS_UPDATE = 'USER_DETAILS_UPDATE';
export const USER_AUTHENTICATE_PROVIDER = 'USER_AUTHENTICATE_PROVIDER';
