export const CHARACTERS_LIST = 'CHARACTERS_LIST';
export const CHARACTERS_GET_LIST = 'CHARACTERS_GET_LIST';
export const CHARACTER_LOGIN = 'CHARACTER_LOGIN';
export const CHARACTER_CREATE = 'CHARACTER_CREATE';
export const ACCOUNT_LOGOUT = 'ACCOUNT_LOGOUT';
export const ACCOUNT_AUTHENTICATE = 'ACCOUNT_AUTHENTICATE';
export const ACCOUNT_AUTHENTICATE_SUCCESS = 'ACCOUNT_AUTHENTICATE_SUCCESS';
