export const CONNECTION_STATUS = 'CONNECTION_STATUS';
export const CONNECTION_SOCKET = 'CONNECTION_SOCKET';
export const SOCKET_CONNECT = 'SOCKET_CONNECT';
export const SOCKET_SEND = 'SOCKET_SEND';
export const SOCKET_LOGOUT = 'SOCKET_LOGOUT';
export const NOTIFICATION_CLEAR = 'NOTIFICATION_CLEAR';
export const LOADING_SET = 'LOADING_SET';
export const LOADING_CLEAR = 'LOADING_CLEAR';
