export const CHARACTER_ADD = 'CHARACTER_ADD';
export const CHARACTER_REMOVE = 'CHARACTER_REMOVE';
export const CHARACTER_UPDATE = 'CHARACTER_UPDATE';
export const CLIENT_LOAD_CHARACTER = 'CLIENT_LOAD_CHARACTER';
export const CLIENT_UPDATE_CHARACTER = 'CLIENT_UPDATE_CHARACTER';
export const CLIENT_CREATE_CHARACTER = 'CLIENT_CREATE_CHARACTER';
export const CLIENT_CHARACTER_CREATED = 'CLIENT_CHARACTER_CREATED';

export const CLIENT_LOAD_PLAYERLIST = 'CLIENT_LOAD_PLAYERLIST';
export const CLIENT_ADD_TO_PLAYERLIST = 'CLIENT_ADD_TO_PLAYERLIST';
export const CLIENT_REMOVE_FROM_PLAYERLIST = 'CLIENT_REMOVE_FROM_PLAYERLIST';
export const CLIENT_MOVE_CHARACTER = 'CLIENT_MOVE_CHARACTER';
export const CLIENT_EQUIP_ITEM = 'CLIENT_EQUIP_ITEM';
export const CLIENT_UNEQUIP_ITEM = 'CLIENT_UNEQUIP_ITEM';