export const CHARACTER_ADD = 'CHARACTER_ADD';
export const CHARACTER_REMOVE = 'CHARACTER_REMOVE';
export const CLIENT_LOAD_CHARACTER = 'CLIENT_LOAD_CHARACTER';
export const CLIENT_UPDATE_CHARACTER = 'CLIENT_UPDATE_CHARACTER';