export const ACCOUNT_AUTHENTICATE = 'ACCOUNT_AUTHENTICATE';
export const ACCOUNT_AUTHENTICATE_ERROR = 'ACCOUNT_AUTHENTICATE_ERROR';
export const ACCOUNT_AUTHENTICATE_SUCCESS = 'ACCOUNT_AUTHENTICATE_SUCCESS';