export const SERVER_LOAD_MAP = 'SERVER_LOAD_MAP';
export const CLIENT_FETCH_MAPS = 'CLIENT_FETCH_MAPS';
export const CLIENT_UPDATE_LOCATION = 'CLIENT_UPDATE_LOCATION';
export const CLIENT_LOAD_PLAYER_MAP = 'CLIENT_LOAD_PLAYER_MAP';
export const CLIENT_LEAVE_GRID = 'CLIENT_LEAVE_GRID';
export const CLIENT_JOIN_GRID = 'CLIENT_JOIN_GRID';
export const CLIENT_LOAD_GRID = 'CLIENT_LOAD_GRID';