export const CLIENT_TO_SERVER = 'CLIENT_TO_SERVER';
export const SERVER_TO_CLIENT = 'SERVER_TO_CLIENT';

// CONSTANTS SHARED WITH THE CLIENT - how, we will figure out later
export const CLIENT_NOTIFICATION = 'CLIENT_NOTIFICATION';
export const CLIENT_AUTH_SUCCESS = 'CLIENT_AUTH_SUCCESS';
export const CLIENT_NEW_CHARACTER = 'CLIENT_NEW_CHARACTER';
export const CLIENT_NEW_EVENT = 'CLIENT_NEW_EVENT';